"""
Creator Agent for Monsterrr.
"""


import os
from typing import Dict, Any
import base64

class CreatorAgent:
    """
    Agent for creating new repositories and scaffolding projects.
    Uses github_service to create repo, scaffold files, commit, and open starter issues.
    """
    def __init__(self, github_service, logger):
        self.github_service = github_service
        self.logger = logger

    def create_repository(self, idea: Dict[str, Any]) -> None:
        """
        Create a new repository for the given idea, scaffold files, and open starter issues.
        Args:
            idea (dict): Idea metadata (name, description, roadmap, etc.)
        """
        name = idea.get("name")
        description = idea.get("description", "")
        tech_stack = idea.get("tech_stack", [])
        roadmap = idea.get("roadmap", [])
        self.logger.info(f"[CreatorAgent] Creating repository for {name}")
        try:
            repo = self.github_service.create_repository(name, description)
            self.logger.info(f"[CreatorAgent] Repo created: {repo.get('html_url')}")
            # Scaffold files
            self._scaffold_files(name, description, roadmap, tech_stack)
            # Open starter issues
            self._open_starter_issues(name, roadmap)
        except Exception as e:
            self.logger.error(f"[CreatorAgent] Error creating repo: {e}")

    def _scaffold_files(self, repo: str, description: str, roadmap: list, tech_stack: list):
        """Create README.md, LICENSE, .gitignore, main.py, and CI config."""
        readme = f"# {repo}\n\n{description}\n\n## Tech Stack\n{', '.join(tech_stack)}\n\n## Roadmap\n" + '\n'.join(f"- {item}" for item in roadmap)
        license_text = self._get_mit_license()
        gitignore = self._get_python_gitignore()
        main_py = '# Entry point for the project\n\nif __name__ == "__main__":\n    print("Hello from {repo}")\n'
        ci_yaml = self._get_github_actions_yaml()
        files = {
            "README.md": readme,
            "LICENSE": license_text,
            ".gitignore": gitignore,
            f"{repo}/main.py": main_py,
            ".github/workflows/ci.yml": ci_yaml,
        }
        for path, content in files.items():
            try:
                self.github_service.create_or_update_file(repo, path, content, commit_message=f"Add {path}")
                self.logger.info(f"[CreatorAgent] Added {path}")
            except Exception as e:
                self.logger.error(f"[CreatorAgent] Error adding {path}: {e}")

    def _open_starter_issues(self, repo: str, roadmap: list):
        """Open 'good first issues' based on roadmap."""
        for item in roadmap:
            try:
                self.github_service.create_issue(repo, title=f"[good first issue] {item}", body="Auto-generated by Monsterrr.", labels=["good first issue"])
                self.logger.info(f"[CreatorAgent] Opened issue: {item}")
            except Exception as e:
                self.logger.error(f"[CreatorAgent] Error opening issue for {item}: {e}")

    def _get_mit_license(self) -> str:
        """Return MIT license text."""
        return (
            "MIT License\n\nCopyright (c) 2025 ni-sh-a-char\n\nPermission is hereby granted, free of charge, to any person obtaining a copy "
            "of this software and associated documentation files (the \"Software\"), to deal in the Software without "
            "restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, "
            "and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to "
            "the following conditions:\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED."
        )

    def _get_python_gitignore(self) -> str:
        """Return a standard Python .gitignore."""
        return (
            "__pycache__/\n*.py[cod]\n*.env\n.venv/\n.env/\n.DS_Store\n*.log\n*.sqlite3\n" 
            "# Byte-compiled / optimized / DLL files\n__pycache__/\n*.py[cod]\n*$py.class\n" 
            "# Distribution / packaging\nbuild/\ndist/\n.eggs/\n*.egg-info/\n" 
            "# VSCode\n.vscode/\n"
        )

    def _get_github_actions_yaml(self) -> str:
        """Return a basic GitHub Actions CI config for Python."""
        return (
            "name: CI\n\non: [push, pull_request]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n"
            "      - name: Set up Python\n        uses: actions/setup-python@v4\n        with:\n          python-version: '3.11'\n"
            "      - name: Install dependencies\n        run: |\n          python -m pip install --upgrade pip\n          pip install -r requirements.txt\n"
            "      - name: Run tests\n        run: |\n          pytest\n"
        )

if __name__ == "__main__":
    import logging
    from services.github_service import GitHubService
    from utils.logger import setup_logger
    logger = setup_logger()
    github = GitHubService(logger=logger)
    agent = CreatorAgent(github, logger)
    # Example idea
    idea = {
        "name": "SampleProject",
        "description": "A sample project created by Monsterrr.",
        "tech_stack": ["Python", "FastAPI"],
        "roadmap": ["Set up project structure", "Add CI", "Write docs"]
    }
    agent.create_repository(idea)
